### ISSUE TITLE
Error: Loading chunk game failed.

### ISSUE THREAD

**Issue by maryamBaratii** [Sun0fABeach/vue-phaser3#11]
Hi..I have a problem when working on project on serve mode using vue-cli-service serve. When I open the application, thus the chunk game is loaded but when I change something in the application and reload the page I get this error..

Error in mounted hook (Promise/async): "ChunkLoadError: Loading chunk game failed.

![Screenshot from 2021-04-10 13-59-44](https://user-images.githubusercontent.com/43367298/114265255-0d162080-9a05-11eb-856c-e1ea5e41195a.png)

**Comment by Sun0fABeach** [comment]
Hi. I can't reproduce this myself. What Browser and OS are you using on what versions?
`net::ERR_CACHE_WRITE_FAILURE` looks curious. Have you tried clearing your cache or using another browser? Will this give you the same result?

**Comment by maryamBaratii** [comment]
I'm using Chrome version 70.0.3538.77 and Ubuntu 18.04 and Yes I have tried clearing my cache and the error has been fixed. But every time I change something and reload the page or when I change route, I get this error and I should clear my cache again.
I`ve tried with firefox v87.0 and the error did not occurred..

Thank you for your help..

**Comment by Sun0fABeach** [comment]
Sorry for the late reply, but I think you're using a pretty outdated Chrome version. According to [this](https://en.wikipedia.org/wiki/Google_Chrome_version_history) site, it is more than 2.5 years old. Could you try updating to the latest Chrome and see if the problem persists? The latest version is 90.0.4430 as I write this.
