### ISSUE TITLE
Module build failed: SyntaxError: 'import' and 'export' may only appear at the top level (20:4) 

### ISSUE THREAD

**Issue by K-marad** [Sun0fABeach/vue-phaser3#2]
Hello,
It's more a question than really an issue.
I didn't use all of your code, but tried to integrate most of it to my current project.

in Game.vue, in the mounted() event, you did this :

```javascript
mounted() {
    import(/* webpackChunkName: "game" */ '@/game/game').then(game => {
      this.downloaded = true
      this.$nextTick(() => game.launch())
    })
  }
``` 

There it crashes for me, stating that import can only appear at top level.
But then I notice there is an annotation for webpack...
Any lead on how this works ?

Thanks

**Comment by Sun0fABeach** [comment]
Hi,
can you give some information about your setup? Is your project based on this template? If not, do you use Webpack or a Vue-CLI template? 
My guess is that you haven't set up babel properly and your dynamic imports are not being transpiled.

**Comment by K-marad** [comment]
I'm using a vue-cli template, I started my project this way :
```vue init webpack web_app_client```

I haven't set up babel at all actually.

Is the problem there :

```

module.exports = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'file-loader',
        /*options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }*/
      },
...
```
Should I replace 'vue-loader' by something related to babel  ?

**Comment by Sun0fABeach** [comment]
Ok, I see one major problem here:
You have initialized your repo using the **vue init** command, which is deprecated and only exists for some legacy reasons. Furthermore, the [template](https://github.com/vuejs-templates/webpack) you chose has not been maintained for about a year, which means that even if we fix your babel issue, there will likely be others around the corner.

The way I integrated Phaser with Vue is to set up a proper Vue-CLI 3 project using **vue create** and then tweaking the generated Webpack config to make it play nice with Phaser. So if you want achieve the same integration in your project, I strongly recommend recreating it using **vue create** and applying the Webpack modifications that I've done in _vue.config.js_. Or even better, just clone my repo and move your code into it.

**Comment by K-marad** [comment]
Oh okay, glad to learn that now rather than when the code base is huge. Thank you!

**Comment by Sun0fABeach** [comment]
It is easy to install vue router on top of my template. The Vue CLI has a [plugin system](https://cli.vuejs.org/guide/plugins-and-presets.html#plugins). Just do this:

`vue add router`

If you want auto reload on changes, add this to your _vue.config.js_ (already done in my template):

```
devServer: {
    open: true,
    hot: false
}
```

Beware that hot reloading will not work with Phaser, so I deactivated that.

**Comment by K-marad** [comment]
I tried to change that 'hot' to true, but it doesn't work. Setting a environment variable "NODE_ENV" to development doesn't help either. It's fine if I have to refresh the webpage to test phaser.

**Comment by Sun0fABeach** [comment]
That's weird, webpack usually does a live reload by default. Can you check if your _vue.config.js_ looks exactly like mine?

**Comment by K-marad** [comment]
it is exactly yours actually.

**Comment by K-marad** [comment]
Problem fixed by editing vue.config.js :
```
module.exports = {
  chainWebpack: config => {
    /* disable insertion of assets as data urls b/c Phaser doesn't support it */
    const rules = [
      { name: 'images', dir: 'img' },
      { name: 'media',  dir: 'media' }
    ]
    rules.forEach(rule => {
      const ruleConf = config.module.rule(rule.name)

      ruleConf.uses.clear()

      ruleConf
        .use('file-loader')
          .loader('file-loader')
          .options({
            name: `${rule.dir}/[name].[hash:8].[ext]`
          })
    })
  },
  devServer: {
    hot: true,
    watchOptions: { 
      aggregateTimeout: 300, 
      poll: true 
    }
  }
}
```

**Comment by Sun0fABeach** [comment]
Interesting, looks like Webpack doesn't get notified of file changes on your system. I'm glad the polling option is working for you!

**Comment by K-marad** [comment]
Yes I think it depends on the text editor, apparently some create a temporary file and rename it on save.
And I guess the hook of the dev server doesn't take this into account.
So yes, the polling does the job. It probably does eat some more resources though, but that's fine.

**Comment by Sun0fABeach** [comment]
Very well. Closing this.

Good luck!

**Comment by K-marad** [comment]
Thank you man.
