### ISSUE TITLE
"unmounted" to be used instead of "destroyed" in Vue 3

### ISSUE THREAD

**Issue by lewweiming** [Sun0fABeach/vue-phaser3#25]
Hi, thank you for providing this template. It's really helpful. :)

There's a small issue I'd like to point out with the current source.

```
// game.vue
unmounted() {
  this.gameInstance.destroy(false)
}
```

**Comment by Sun0fABeach** [comment]
Great catch, didn't notice that when upgrading to Vue 3. Fix is pushed.
