### ISSUE TITLE
import for game fails on Heroku

### ISSUE THREAD

**Issue by DylanC** [Sun0fABeach/vue-phaser3#4]
This line causes an error on Heroku deployment:
`const game = await import(/* webpackChunkName: "game" */ '@/game')`

```
This dependency was not found:
       
       * @/game in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Game.vue?vue&type=script&lang=js&
       
       To install it, you can run: npm install --save @/game
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rev1-frontend@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rev1-frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.o4QiG/_logs/2020-05-26T10_47_11_732Z-debug.log
-----> Build failed
```

Same line of code is working on local dev and local build.

**Comment by Sun0fABeach** [comment]
Hi.
It looks like you changed this line. The original one in the template is:

`const game = await import(/* webpackChunkName: "game" */ '@/game/game')`

You need to import `@/game/game`, not `@/game`.

Can you fix that and try again, pls?

**Comment by DylanC** [comment]
@Sun0fABeach - Okay, I got your master working on Heroku. (PR submitted) My project which includes your code doesn't work even if I change it back to the following:

`const game = await import(/* webpackChunkName: "game" */ '@/game/game')`

```
 -  Building legacy bundle for production...
remote:         ERROR  Failed to compile with 1 errors12:09:02 PM
remote:        
remote:        This dependency was not found:
remote:        
remote:        * @/game/game in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Game.vue?vue&type=script&lang=js&
```
Note I am launching my app with this:
`"start": "node web-server.js",`

Your project uses serve instead:
`"start": "serve dist",`

Could this be the cause of the issue?

**Comment by DylanC** [comment]
@Sun0fABeach - Got it working but I had to move `/game` into `/views/game` and change the import to this:
`./game/game`

**Comment by Sun0fABeach** [comment]
> Note I am launching my app with this:
> "start": "node web-server.js",
>
> Your project uses serve instead:
> "start": "serve dist",
>
> Could this be the cause of the issue?

I put the 'serve' package in to enable local production build testing. If you choose to use it to launch your app in your hosting environment, you need to make sure it's installed there. In case of Heroku this means you have to move it to the (non-dev) dependencies, which you already figured out.

> @Sun0fABeach - Got it working but I had to move /game into /views/game and change the import to this:
> ./game/game

I can't really comment on this since I'm not familiar with your project structure. I'm glad you got it working, though.
